log:
  level: info
  format: json

api:
  port: 9099

flow:
  name: "my-flow"
  type: async
  in_memory_queue_max_size: 1000
  max_concurrent_uploads: 50
  max_retries: 3
  timeout: 120
  accumulator:
    size_in_bytes: 2097152 # 2MB
    separator: "__n__"
    queue_capacity: 0
  external_queue:
    type: sqs
    config:
      url: "queue-url"
      region: aws-region-here
      access_key: ""
      secret_key: ""
  object_storage:
    type: s3
    config:
      bucket: some-bucket-name-here
      region: aws-region-here
      endpoint: ""
      access_key: ""
      secret_key: ""

#tracing config


# type: S3
# config:
#   bucket: ""
#   endpoint: ""
#   region: ""
#   aws_sdk_auth: false
#   access_key: ""
#   insecure: false
#   signature_version2: false
#   secret_key: ""
#   put_user_metadata: {}
#   http_config:
#     idle_conn_timeout: 1m30s
#     response_header_timeout: 2m
#     insecure_skip_verify: false
#     tls_handshake_timeout: 10s
#     expect_continue_timeout: 1s
#     max_idle_conns: 100
#     max_idle_conns_per_host: 100
#     max_conns_per_host: 0
#     tls_config:
#       ca_file: ""
#       cert_file: ""
#       key_file: ""
#       server_name: ""
#       insecure_skip_verify: false
#     disable_compression: false
#   trace:
#     enable: false
#   list_objects_version: ""
#   bucket_lookup_type: auto
#   part_size: 67108864
#   sse_config:
#     type: ""
#     kms_key_id: ""
#     kms_encryption_context: {}
#     encryption_key: ""
#   sts_endpoint: ""
# prefix: ""
