name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.1"
        cache: true
    - name: Test
      run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.1"
        cache: true
    - name: Lint
      run: make lint

  e2e-aws:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.1"
        cache: true
    - name: Local-E2E tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        JIBOIA_S3_BUCKET: ${{ secrets.JIBOIA_S3_BUCKET }}
        JIBOIA_SQS_URL: "${{ secrets.JIBOIA_SQS_URL }}"
      run: make test-e2e-aws-ci
