name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18.5"
        cache: true
    - name: Test
      run: make test

  lint:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18.5"
        cache: true
    - name: Lint
      run: make lint
