name: Release Go project

on:
  push:
    tags:
      - "*"

jobs:
  vuln:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20.7"
        cache: true
    - name: Test
      run: make vuln

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.7"
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: "./cmd"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
